wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.12
    session_history: code/_session_history.ipynb
    start_time: 1673002040
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.7.12
      5: 0.12.21
      8:
      - 1
      - 2
      - 5
    visualize:
      age_hist:
        panel_config:
          fieldSettings:
            value: Age
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Age Distribution
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: age_hist_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      age_hist_cancer:
        panel_config:
          fieldSettings:
            value: Age
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Age Distribution - patients with cancer
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: age_hist_cancer_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
_wandb_kernel:
  desc: null
  value: aot
competition:
  desc: null
  value: RSNA_Breast_Cancer
