wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.12
    session_history: code/_session_history.ipynb
    start_time: 1673002095
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.7.12
      5: 0.12.21
      8:
      - 1
      - 2
      - 5
_wandb_kernel:
  desc: null
  value: aot
competition:
  desc: null
  value: RSNA_Breast_Cancer
